# epc sdk 公共配置 sdk方维护
epc:
  cache:
    redis: true
  sdk:
    user-host: http://10.80.252.68:9001
    meta-host: http://10.80.252.68:9002
    file-host: http://10.80.252.68:9998
    node-host: http://10.80.252.68:9003
    component-host: http://10.80.252.68:9004
    easyapi-host: http://10.80.253.140:8080
    easyapi-token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHBpcmVfdGltZSI6MTcwOTg2MDMzNzMxNH0.QlitfW6yTqbLwsX4bkZSBzv6AkG_lhet8eRTSp-NDUM
  # UC 相关
  uc:
    operationUrl: http://localhost:8080/
    UcUrl: https://test6.cbim.org.cn/passport/
cbim:
  uc:
    sdk:
      type: WS
      host: test6 #！！！随环境变化
      port: 30091 #每个环境固定
      #zkUrl: 10.80.252.168:2181 #已废弃zk
      enable: true #开关
      #type为ws、app时生效
      UcUrl: https://test6-gw.cbim.org.cn/cbim-uc #uc网关地址！！！随环境变化
      #UcUrl: https://test6.cbim.org.cn/passport/ #uc网关地址！！！随环境变化
      system: xboat#系统code，八仙xboat，马良xcube，云渲染rendering
      #在uc注册的系统appKey和secret，type为uc时不生效
      key: e3c091d7c0ef42d49ac9b598475e478a #每个系统不一样，每个环境一样
      secret: adf207306aca4c81ae5eb0cf57252f29 #每个系统不一样，每个环境一样
      filter: true
